name: Auto Merge DB Branches

on:
  push:
    branches:
      - dev-db
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-db-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "${{ secrets.PROD_GRUPO3 }}"
          git config user.email "ci-bot@users.noreply.github.com"

      - name: Set remote with PAT
        run: |
          git remote set-url origin "https://${{ secrets.PROD_GRUPO3 }}:${{ secrets.PROD_PAT }}@github.com/grupog849-netizen/proyecto-ubuntu.git"
          git fetch origin --prune

      - name: Merge dev-db → staging
        run: |
          git checkout -B staging origin/staging
          git merge -X theirs --no-ff --no-edit origin/dev-db || true
          git push origin HEAD:staging

  pr-staging-to-main:
    needs: merge-db-to-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set remote with PAT
        run: |
          git remote set-url origin "https://${{ secrets.PROD_GRUPO3 }}:${{ secrets.PROD_PAT }}@github.com/grupog849-netizen/proyecto-windows.git"
          git fetch origin --prune

      - name: Create PR staging → main (DB)
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto-PR (DB): staging → main"
          body: "Cambios automáticos del módulo Base de Datos"
          commit-message: "chore(DB): sync staging → main"
          base: main
          branch: ci/auto-pr-db-staging-to-main
          delete-branch: true
          draft: false

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
